# GitHub Pages Configuration
title: "Amir Mulani - Portfolio"
description: "Professional portfolio showcasing React Native development skills"
baseurl: ""
url: "https://amir-313.github.io"

# Build settings
markdown: kramdown
highlighter: rouge
theme: minima

# Exclude from processing
exclude:
  - README.md
  - create-placeholders.html
  - .gitignore
  - _config.yml
